export default {
    sliders: [
        {
            label: 'Basic Shape-1',
            key: 'basicShape-1',
            min: 1,
            init: 1,
            max: 4,
            step: 1,
            precision: 0,
        },
        {
            label: 'Basic Shape Size-1',
            key: 'basicShapeSize-1',
            min: 1,
            init: 1,
            max: 15,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Shape-1',
            key: 'screenSplitShape-1',
            min: 1,
            init: 1,
            max: 3,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Num-1',
            key: 'screenSplitNum-1',
            min: 1,
            init: 1,
            max: 12,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Spread-1',
            key: 'screenSplitSpread-1',
            min: 2,
            init: 4,
            max: 12,
            step: 1,
            precision: 0,
        },
        {
            label: 'Shape Hue-1',
            key: 'shapeHue-1',
            min: 0,
            init: 180,
            max: 360,
            step: 10,
            precision: 0,
        },
        {
            label: 'Offset X-1',
            key: 'offsetX-1',
            min: 0,
            init: 0,
            max: 30,
            step: 1,
            precision: 0,
        },
        {
            label: 'Offset Y-1',
            key: 'offsetY-1',
            min: 0,
            init: 0,
            max: 30,
            step: 1,
            precision: 0,
        },
        {
            label: 'Basic Shape-2',
            key: 'basicShape-2',
            min: 1,
            init: 1,
            max: 4,
            step: 1,
            precision: 0,
        },
        {
            label: 'Basic Shape Size-2',
            key: 'basicShapeSize-2',
            min: 1,
            init: 1,
            max: 15,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Shape-2',
            key: 'screenSplitShape-2',
            min: 1,
            init: 1,
            max: 3,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Num-2',
            key: 'screenSplitNum-2',
            min: 1,
            init: 1,
            max: 12,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Spread-2',
            key: 'screenSplitSpread-2',
            min: 2,
            init: 4,
            max: 12,
            step: 1,
            precision: 0,
        },
        {
            label: 'Shape Hue-2',
            key: 'shapeHue-2',
            min: 0,
            init: 180,
            max: 360,
            step: 10,
            precision: 0,
        },
        {
            label: 'Offset X-2',
            key: 'offsetX-2',
            min: 0,
            init: 0,
            max: 30,
            step: 1,
            precision: 0,
        },
        {
            label: 'Offset Y-2',
            key: 'offsetY-2',
            min: 0,
            init: 0,
            max: 30,
            step: 1,
            precision: 0,
        },
    ],
};
